### ISSUE TITLE
Is the repo still being maintained?

### ISSUE THREAD

**Issue by zhiyong-ft** [janjongboom/mbed-ws#1]
Hi,

I stumbled upon your repo when I was searching for wss client for mbed. 

It would be nice if there is an out of box wss client. Until that happens, what is the problem of replacing the TCPSocket with TLSSocket in official WsClient?
https://os.mbed.com/teams/mbed_example/code/WebSocketClient/

I assume it will be easier than starting from scratch.

Please advise. Thanks.

**Comment by janjongboom** [comment]
@zhiyong80 We use this internally at Edge Impulse, and it works fine (but we don't need wss) - so I don't expect to add anything to the library anytime soon.

> It would be nice if there is an out of box wss client. Until that happens, what is the problem of replacing the TCPSocket with TLSSocket in official WsClient?

Sure, probably works, but that library is blocking. We needed a client which supported async operations and do some extra things like disconnect detection and ping/pong. Also calling it the 'official' client is a stretch - it's not maintained.

**Comment by zhiyong-ft** [comment]
Thanks for information. I didn't realize the 'official' client was not maintained and cannot even compile on mbed-os 5 and 6 until recently. Since we will need wss, I guess we will have to implement a client by ourselves.

Good luck with your new endeavor at Edge Impulse.

**Comment by janjongboom** [comment]
Hi @zhiyong80 Have you tried the implementation in this repo? There's a WSS client in here that uses TLSSocket underneath.
